---
deployment:
  tasks:
    - export DEPLOYPATH=/home/beegeniu/public_html/
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R db $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
